version: '3.8'

services:
  # 1. Ton Application Trace-X (Serveur Web)
  app:
    image: trace-x-app:latest
    container_name: tracex_server
    restart: always
    network_mode: "host"
    privileged: true
    pids_limit: 4096
    mem_limit: 1024m
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - .:/app
    command: python3 app.py

  # 2. Le Dashboard de Monitoring (Glances)
  monitor:
    image: nicolargo/glances:latest-full
    container_name: tracex_dashboard
    restart: always
    pid: host
    network_mode: "host"
    environment:
      - "GLANCES_OPT=-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # 3. Le Terminal (Pour tes commandes manuelles)
  terminal:
    image: trace-x-app:latest
    container_name: tracex_terminal
    network_mode: "host"
    privileged: true
    pids_limit: 4096
    command: tail -f /dev/null